#spring:
 # kafka:
  #  bootstrap-servers: snapdev-instance-02-5063.ccg21.dev.paypalcorp.com:9092
    #localhost:9092, ,snapdev-instance-03-5105.ccg21.dev.paypalcorp.com:9092,snapdev-instance-04-4111.ccg21.dev.paypalcorp.com:9092

#app:
 # topic:
  #  foo: kafka.topic
    #foo.t

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.memorynotfound: DEBUG