#spring:
 # kafka:
  #  bootstrap-servers: abc:9092
    #localhost:9092, ,abc:9092,abc:9092

#app:
 # topic:
  #  foo: kafka.topic
    #foo.t

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.memorynotfound: DEBUG
